# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "zymbot"
mod.name = "Zymbot"
mod.group = "dev.yuliang"
mod.version = "0.1.40"

deps.fabric_loader = "0.19.3"
loomx.loom_version = "1.17-SNAPSHOT"

["1.21.1"]
mod.mc_compat = ">=1.21 <=1.21.1"
mod.mc_releases = ["1.21", "1.21.1"]
deps.fabric_api = "0.116.15+1.21.1"
deps.modmenu = "11.0.4"
deps.baritone = "1.11.3"
